#!/usr/bin/env python3
"""Read original SCDM interfaces and a symmetry package, initialize, and run SAWF without WAVECAR."""
import argparse
import sys
from pathlib import Path


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--seed', required=True, type=Path, help='Common prefix of the original WIN/MMN/AMN/EIG files')
    parser.add_argument('--symmetry', required=True, type=Path, help='Symmetry package directory generated by the extraction step')
    parser.add_argument('--center', required=True, nargs=3, type=float, metavar=('X','Y','Z'), help='Fractional coordinates of the target center')
    parser.add_argument('--orbital', required=True, help='Target local representation in WannierBerri, such as t2g')
    parser.add_argument('--output', required=True, type=Path, help='New model output directory')
    parser.add_argument('--num-iter', type=int, default=1000, help='Maximum localization iterations')
    parser.add_argument('--dft-eigenval', type=Path, help='Optional DFT path EIGENVAL for exporting data for the three band plots')
    parser.add_argument('--energy-reference-ev', type=float, default=0., help='Shared plot energy reference; defaults to absolute energies')
    args = parser.parse_args()
    from core.localize import run_sawf
    try:
        report = run_sawf(args.seed, args.symmetry, args.output,
                          center=args.center, orbital=args.orbital, num_iter=args.num_iter,
                          dft_eigenval=args.dft_eigenval,
                          energy_reference_ev=args.energy_reference_ev)
    except (ValueError, OSError, RuntimeError) as error:
        print(f'SAWF failed: {error}', file=sys.stderr)
        return 1
    print(f"Model: {args.output.resolve()}; status: {report['status']}; converged: {report['converged']}")
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
